"""async-ffmpeg — асинхронная, строго типизированная библиотека-обёртка над FFmpeg и FFprobe."""

from async_ffmpeg._compat import (
    escape_filter_path,
    normalize_path_for_ffmpeg,
    terminate_process_gracefully,
)
from async_ffmpeg._constants import (
    DEFAULT_AUDIO_BITRATE,
    DEFAULT_FFMPEG_EXECUTABLE,
    DEFAULT_FFPROBE_EXECUTABLE,
    DEFAULT_LOGLEVEL,
    DEFAULT_MAX_CONCURRENT,
    DEFAULT_STATS_PERIOD,
    DEFAULT_VIDEO_CRF,
    DEFAULT_VIDEO_PRESET,
    __version__,
)
from async_ffmpeg._discovery import (
    BinaryInfo,
    clear_discovery_cache,
    find_binary,
    find_ffmpeg,
    find_ffprobe,
    get_binary_version,
    get_binary_version_sync,
    get_ffmpeg_info,
    get_ffprobe_info,
)
from async_ffmpeg._types import (
    ConcatMethod,
    DownloadResultProtocol,
    LogLevel,
    MediaInputProtocol,
    PathLike,
    ProgressCallback,
    StderrCallback,
    StreamType,
    VideoPreset,
)
from async_ffmpeg.exceptions import (
    AsyncFFmpegError,
    CodecNotFoundError,
    CommandBuildError,
    FFmpegCancelledError,
    FFmpegNotFoundError,
    FFmpegProcessError,
    FFmpegTimeoutError,
    FFprobeError,
    FilterError,
    InvalidInputError,
)
from async_ffmpeg.process import ProcessResult, ProcessRunner
from async_ffmpeg.progress import ProgressInfo, ProgressParser, parse_progress_stream

__all__ = [
    "DEFAULT_AUDIO_BITRATE",
    "DEFAULT_FFMPEG_EXECUTABLE",
    "DEFAULT_FFPROBE_EXECUTABLE",
    "DEFAULT_LOGLEVEL",
    "DEFAULT_MAX_CONCURRENT",
    "DEFAULT_STATS_PERIOD",
    "DEFAULT_VIDEO_CRF",
    "DEFAULT_VIDEO_PRESET",
    "AsyncFFmpegError",
    "BinaryInfo",
    "CodecNotFoundError",
    "CommandBuildError",
    "ConcatMethod",
    "DownloadResultProtocol",
    "FFmpegCancelledError",
    "FFmpegNotFoundError",
    "FFmpegProcessError",
    "FFmpegTimeoutError",
    "FFprobeError",
    "FilterError",
    "InvalidInputError",
    "LogLevel",
    "MediaInputProtocol",
    "PathLike",
    "ProcessResult",
    "ProcessRunner",
    "ProgressCallback",
    "ProgressInfo",
    "ProgressParser",
    "StderrCallback",
    "StreamType",
    "VideoPreset",
    "__version__",
    "clear_discovery_cache",
    "escape_filter_path",
    "find_binary",
    "find_ffmpeg",
    "find_ffprobe",
    "get_binary_version",
    "get_binary_version_sync",
    "get_ffmpeg_info",
    "get_ffprobe_info",
    "normalize_path_for_ffmpeg",
    "parse_progress_stream",
    "terminate_process_gracefully",
]
