"""async-ffmpeg — асинхронная, строго типизированная библиотека-обёртка над FFmpeg и FFprobe."""

from async_ffmpeg._constants import (
    DEFAULT_AUDIO_BITRATE,
    DEFAULT_FFMPEG_EXECUTABLE,
    DEFAULT_FFPROBE_EXECUTABLE,
    DEFAULT_LOGLEVEL,
    DEFAULT_MAX_CONCURRENT,
    DEFAULT_STATS_PERIOD,
    DEFAULT_VIDEO_CRF,
    DEFAULT_VIDEO_PRESET,
    __version__,
)
from async_ffmpeg._types import (
    ConcatMethod,
    DownloadResultProtocol,
    LogLevel,
    MediaInputProtocol,
    PathLike,
    ProgressCallback,
    StderrCallback,
    StreamType,
    VideoPreset,
)
from async_ffmpeg.exceptions import (
    AsyncFFmpegError,
    CodecNotFoundError,
    CommandBuildError,
    FFmpegCancelledError,
    FFmpegNotFoundError,
    FFmpegProcessError,
    FFmpegTimeoutError,
    FFprobeError,
    FilterError,
    InvalidInputError,
)

__all__ = [
    "DEFAULT_AUDIO_BITRATE",
    "DEFAULT_FFMPEG_EXECUTABLE",
    "DEFAULT_FFPROBE_EXECUTABLE",
    "DEFAULT_LOGLEVEL",
    "DEFAULT_MAX_CONCURRENT",
    "DEFAULT_STATS_PERIOD",
    "DEFAULT_VIDEO_CRF",
    "DEFAULT_VIDEO_PRESET",
    "AsyncFFmpegError",
    "CodecNotFoundError",
    "CommandBuildError",
    "ConcatMethod",
    "DownloadResultProtocol",
    "FFmpegCancelledError",
    "FFmpegNotFoundError",
    "FFmpegProcessError",
    "FFmpegTimeoutError",
    "FFprobeError",
    "FilterError",
    "InvalidInputError",
    "LogLevel",
    "MediaInputProtocol",
    "PathLike",
    "ProgressCallback",
    "StderrCallback",
    "StreamType",
    "VideoPreset",
    "__version__",
]
